springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    path: /swagger
    display-request-duration: true
    display-operation-id: true
    doc-expansion: false
    tags-sorter: alpha
    operations-sorter: alpha
